(async function main () {
    try {
        console.log('end')
    } catch (e) {
        console.error(e)
    }
})()
